In [9]:
sets = {}
class DataSet():
    # Rocket simulates a rocket ship for a game,
    #  or a physics simulation.
    
    def __init__(self):
        # Each rocket has an (x,y) position.
        self.features = None
        self.target = None

In [10]:
def process_data(file):
    with open(file) as csvfile:
        readCSV = csv.reader(csvfile, delimiter=',')
        data = DataSet()
        data.features = []
        data.target = []
        for row in readCSV:
            data.features.append(list(np.float_(row[0:5])))
            data.target.append(int(row[5]))
    return data

In [11]:
from sklearn.neural_network import MLPClassifier
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

def run_model(data):
    X_train, X_test, y_train, y_test = train_test_split(data.features, data.target, test_size=0.4, random_state=0)
    clf_svm = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
    clf_knn = KNeighborsClassifier(n_neighbors=3)
    clf_nn = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1).fit(X_train, y_train)  
    y_pred_svm = clf_svm.fit(X_train, y_train).predict(X_test)
    y_pred_knn = clf_knn.fit(X_train, y_train).predict(X_test)
    y_pred_nn = clf_nn.fit(X_train, y_train).predict(X_test)
    print('svm', clf_svm.score(X_test, y_test))
    print('knn', clf_knn.score(X_test, y_test))
    print('nn', clf_nn.score(X_test, y_test))
    print("svm confusion matrix")
    print(confusion_matrix(y_test, y_pred_svm))
    print("knn confusion matrix")
    print(confusion_matrix(y_test, y_pred_knn))
    print("nn confusion matrix")
    print(confusion_matrix(y_test, y_pred_nn))


In [13]:
import numpy as np
from sklearn.model_selection import train_test_split
import csv
import glob

    
mouse_rectangle = 'combined/2class/mouse_rectangle.csv' # mouse is 0 and Rectangle is 1
mouse_square = 'combined/2class/mouse_square.csv' # mouse is 0 and square is 1
mouse_tape = 'combined/2class/mouse_tape.csv' # mouse is 0 and tape is 1
square_tape = 'combined/2class/square_tape.csv' # square is 0 and tape is 1
square_rectangle = 'combined/2class/square_rectangle.csv' # square is 0 and Rectangle is 1
rectangle_tape = 'combined/2class/rectangle_tape.csv' # rectangle is 0 and tape is 1
gripperball = 'combined/2class/gripperball_square.csv' # gripperball is 0 and square is 1

mouse_rectangle_data = process_data(mouse_rectangle)
mouse_square_data = process_data(mouse_square)
mouse_tape_data = process_data(mouse_tape)
square_tape_data = process_data(square_tape)
square_rectangle_data = process_data(square_rectangle)
rectangle_tape_data = process_data(rectangle_tape)
gripperball_squaree_data = process_data(gripperball_square)

FileNotFoundError: [Errno 2] No such file or directory: 'combined/2class/mouse_rectangle.csv'

In [24]:
print('Mouse vs Rectangle')
run_model(mouse_rectangle_data)
print("")
print('Mouse vs Square')
run_model(mouse_square_data)
print("")
print('Mouse vs Tape')
run_model(mouse_tape_data)
print("")
print('Square vs Tape')
run_model(square_tape_data)
print("")
print('Square vs Rectangle')
run_model(square_rectangle_data)
print("")
print('Rectangle vs Tape')
run_model(rectangle_tape_data)
print("")
print('Gripperball vs Square')
run_model(gripperball_square_data)
print("")

Mouse vs Rectangle
svm 0.764634146341
knn 0.918902439024
nn 0.77256097561
svm confusion matrix
[[538 299]
 [ 87 716]]
knn confusion matrix
[[760  77]
 [ 56 747]]
nn confusion matrix
[[578 259]
 [114 689]]

Mouse vs Square
svm 0.589024390244
knn 0.848170731707
nn 0.667073170732
svm confusion matrix
[[666 171]
 [503 300]]
knn confusion matrix
[[733 104]
 [145 658]]
nn confusion matrix
[[533 304]
 [242 561]]

Mouse vs Tape
svm 0.918292682927
knn 0.97743902439
nn 0.921951219512
svm confusion matrix
[[751  86]
 [ 48 755]]
knn confusion matrix
[[807  30]
 [  7 796]]
nn confusion matrix
[[771  66]
 [ 62 741]]

Square vs Tape
svm 0.880487804878
knn 0.978048780488
nn 0.884756097561
svm confusion matrix
[[723 114]
 [ 82 721]]
knn confusion matrix
[[808  29]
 [  7 796]]
nn confusion matrix
[[740  97]
 [ 92 711]]

Square vs Rectangle
svm 0.709146341463
knn 0.917682926829
nn 0.74512195122
svm confusion matrix
[[480 357]
 [120 683]]
knn confusion matrix
[[751  86]
 [ 49 754]]
nn confusion matrix
[[5